// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App settings (persisted as a JSON blob in the store's meta table).
 */
export type AppSettings = { 
/**
 * Stats dir override; empty string = auto-detect (default Steam path).
 */
stats_dir: string, 
/**
 * Background sync interval in hours (0 = only manual sync).
 */
sync_interval_hours: number, };
