// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankTier } from "./RankTier";

/**
 * One category row in the benchmark detail view.
 */
export type CategoryCard = { name: string, progress: number, rank_tier: RankTier | null, };
