// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FamilyRowDto } from "./FamilyRowDto";

/**
 * Wire mirror of `kovaaks_core::dashboard::FamilyRow` rollup.
 */
export type DashboardFamiliesDto = { families: Array<FamilyRowDto>, };
