// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FamilyDiffDto } from "./FamilyDiffDto";

export type FamilyRowDto = { benchmark_name: string, color: string, categories: Array<string>, difficulties: Array<FamilyDiffDto>, };
