// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FamilyDiffDto = { difficulty_name: string, kovaaks_id: number, current_rank: number, current_tier: string, tier_names: Array<string>, series: Array<[string, string]>, benchmark_progress: number, };
