// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrindTargetDto } from "./GrindTargetDto";

export type GrindNextDto = { currentRank: string, nextRank: string, 
/**
 * True when the benchmark already sits at the top of its ladder.
 */
complete: boolean, targets: Array<GrindTargetDto>, 
/**
 * Step-by-step plan when no single scenario can flip the rank; together
 * the steps reach the next rank. Empty when `targets` is non-empty.
 */
plan: Array<GrindTargetDto>, };
