// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire DTO for the grind-next panel.
 */
export type GrindTargetDto = { scenario: string, currentScore: number, targetScore: number, delta: number, 
/**
 * Ladder rungs between current and target (1 = a single-tier step).
 */
rungsCrossed: number, 
/**
 * Consistency (CV σ/μ over the recent merged series; None without data).
 */
cv: number | null, 
/**
 * No new personal best for ≥ PLATEAU_DAYS with enough samples.
 */
plateaued: boolean, };
