// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase-2 grind chip payload: the slow grind-engine summary for one
 * difficulty, computed after the overview grid has painted (see
 * `grind_overview`).
 */
export type GrindChipDto = { benchmark_id: number, runs_to_next: number, plateaued: boolean, };
