// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters from the last CSV ingest scan + last sync time.
 *
 * `last_synced_at` is an additive extension of the planned shape; the
 * overview top bar uses it for the last-synced display and the 12h stale
 * badge without a dedicated extra command.
 */
export type IngestStatus = { csv_seen: number, csv_inserted: number, last_synced_at: string | null, };
