// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated metrics for one score series.
 */
export type Metrics = { 
/**
 * Mean of every score in the (windowed) series.
 */
avg_score: number, 
/**
 * Maximum score in the (windowed) series.
 */
high_score: number, 
/**
 * Second-half-of-buckets avg vs first-half-of-buckets avg, in percent.
 */
avg_improvement_pct: number | null, 
/**
 * Current high vs first-bucket high, in percent.
 */
high_improvement_pct: number | null, 
/**
 * Number of samples considered.
 */
samples: number, };
