// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plateau state for a scenario series.
 */
export type PlateauInfo = { days_since_pb: number, plateaued: boolean, 
/**
 * Coefficient of variation over the recent window (0..~1).
 */
cv: number, best: number, };
