// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One CSV play point.
 */
export type PlayPoint = { 
/**
 * Scenario this play belongs to (scoped chart underlay).
 */
scenario: string, played_at: string, score: number, };
