// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rank tier: a display name and its official hex color.
 */
export type RankTier = { name: string, 
/**
 * Hex color string as published by evxl (e.g. `#999999`).
 */
color: string, };
