// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a chart series' points came from — wire form of
 * [`kovaaks_core::metrics::ScenarioSeriesSource`]. Serialized lowercase so
 * the frontend contract is unchanged ("snapshot" | "local").
 */
export type ScenarioHistorySource = "snapshot" | "local";
