// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankTier } from "./RankTier";

/**
 * One scenario row in the benchmark detail view.
 */
export type ScenarioRank = { scenario: string, score: number, leaderboard_rank: number, tier: RankTier | null, 
/**
 * 1-based achieved tier index from the API (0 = unplayed).
 */
scenario_rank: number, 
/**
 * This scenario's tier thresholds (display units), ascending.
 */
rank_maxes: Array<number>, };
