// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One (time, score) point of a scenario's history.
 */
export type ScenarioHistoryPoint = { captured_at: string, score: number, 
/**
 * True when this run came from a local CSV play (magenta dot on the
 * chart); false for a synced snapshot entry.
 */
from_play: boolean, };
