// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlateauInfo } from "./PlateauInfo";
import type { ScenarioHistoryPoint } from "./ScenarioHistoryPoint";
import type { ScenarioHistorySource } from "./ScenarioHistorySource";

/**
 * One scenario's score history across snapshots (per-scenario trends).
 */
export type ScenarioHistorySeries = { scenario: string, category: string, 
/**
 * "snapshot" (synced scores) or "local" (CSV plays — no synced score).
 */
source: ScenarioHistorySource, points: Array<ScenarioHistoryPoint>, 
/**
 * Running-high progression: one point per PB (chronological).
 */
pb_points: Array<ScenarioHistoryPoint>, 
/**
 * Plateau/CV summary for the whole series (see kovaaks consistency).
 */
plateau: PlateauInfo, };
