// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One snapshot-history point.
 */
export type SnapshotPoint = { captured_at: string, benchmark_progress: number, };
