// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire mirror of `kovaaks_core::SyncReport` (core types stay serde-free
 * of UI concerns; core's struct does not derive Serialize).
 */
export type SyncReportDto = { ok: number, failed: number, errors: Array<string>, };
