// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImprovementRowDto } from "./ImprovementRowDto";
import type { LevelStepDto } from "./LevelStepDto";
import type { RankChangeDto } from "./RankChangeDto";

/**
 * Wire mirror of `kovaaks_core::weekly::WeeklyReport`.
 */
export type WeeklyReportDto = { since: string, days_played: number, plays: number, scenarios_played: number, pb_events: number, scored_seconds: number, current_streak: number, xp: number, level_name: string, level: number, level_progress_pct: number, level_steps: Array<LevelStepDto>, plays_per_day: [number, number, number, number, number, number, number], improvements: Array<ImprovementRowDto>, rank_changes: Array<RankChangeDto>, };
